kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: testunited
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/testunited/mysql"
